#!/bin/bash
OUTPUT="alsa_output.usb-Logitech_Logitech_G933_Gaming_Wireless_Headset-00.analog-stereo"
pacmd set-default-sink $OUTPUT
pacmd list-sink-inputs | grep index| while read line
do
	pacmd move-sink-input `echo $line | cut -f2 -d' '` $OUTPUT >/dev/null
done
echo "-h" > /home/user/.config/dasv/config
