#!/bin/bash
OUTPUT="alsa_output.pci-0000_00_1f.3.analog-stereo"
pacmd set-default-sink $OUTPUT
pacmd list-sink-inputs | grep index| while read line
do
	pacmd move-sink-input `echo $line | cut -f2 -d' '` $OUTPUT >/dev/null
done
echo "-s" > /home/user/.config/dasv/config
